#!/bin/bash
#
# Filter script to do simple SVN-like keyword expansion for
# release.
# In contrast to SVN the keywords are REPLACED completely, so no post-processing
# is required for the release branch.
# Also the Mashup templates are changed to include the gpx2map version
# Disadvantage: Not suitable for rolling release.
#
#
# Copyright (C) 2010,2013,2014 Robert Lange <sd2k9@sethdepot.org>
# Licensed under the GNU General Public License, version 3
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see {http://www.gnu.org/licenses/}.
#
#
# Supported Keywords are:
# Number of commits on this branch: $LastChangedRevision$
# Last commit date: $LastChangedDate$


# *** Settings
# Major Version to prepend
MAJOR="0."
# Files to consider as master - fetch version/revcount from this file
# --> Don't use masterfile, use all commits instead so we also catch docu changes
# MASTERFILE="gpx2map"
# Compare against which branch?
COMPBRANCH="master"
# And update the following files
FILESTOCHANGE="gpx2map gpx2map.html"
# Special Handling for the "created with ..." stanca in the templates for this files
FILESCREATEDWITHCHANGE="gpx2map.google.template  gpx2map.osm.template"


# Get commit count for the master file
REVCOUNT=$(git log --pretty=oneline ${COMPBRANCH}.. -- "$MASTERFILE"|wc -l)
VERSION="${MAJOR}${REVCOUNT}"
# Get date for the master file
DATE=$(git log --date=short --pretty=format:"%ad" -1 -- "$MASTERFILE")

# Status infos
echo "Version: ${VERSION}"
echo "Date: ${DATE}"
echo "Files to change: ${FILESTOCHANGE}"


# *** Perform changes
# Change keyword files
for fil in ${FILESTOCHANGE}; do
 echo "Keyword Replacement: Changing $fil ..."
 cp "$fil" "$fil.bak"
 cat "$fil.bak" | \
   sed -e "s/\\\$LastChangedRevision.*\\\$/${VERSION}/g" | \
   sed -e "s/\\\$LastChangedDate.*\\\$/${DATE}/g" > "$fil"
done
# Change Templates
for fil in ${FILESCREATEDWITHCHANGE}; do
 echo "Created-With Replacement: Changing $fil ..."
 cp "$fil" "$fil.bak"
 cat "$fil.bak" | \
   sed -e "s/created with <a href=\"http:\/\/sethdepot.org\/gpx2map\/\">gpx2map<\/a>/created with <a href=\"http:\/\/sethdepot.org\/gpx2map\/\">gpx2map ${VERSION}<\/a>/g" > "$fil"
done

echo "Done"
