#!/bin/bash
# Kleines Script um Distribution zu erstellen
#
# Was vorher Manuell zu machen ist:
# gpx2map.html
# - Revision anpassen in gpx2map.html
# - Datum aktualisieren: htinc gpx2map.html
# - Checkin für Tag-Update


# *** Settings
# Version
VERSION=$(svn status --verbose gpx2map | cut -c 20-27)
# Strip spaces from Version
VERSION=${VERSION#"${VERSION%%[! ]*}"}
# Archivname w/o Suffix
ARC_NAME=gpx2map_0.${VERSION}


# *** File-List aus SVN erstellen
# File-liste
FILES_RAW=$(svn stat -v |grep -v "^?" | cut -c 41-)
FILES_IGNORE=
# Ignore some files
for file in $FILES_RAW; do
   case $file in
   "." | "make_dist" | "TODO" )    ;; # Ignorieren
   *) FILES_IGNORE="$FILES_IGNORE $file" ;;
   esac
done
FILES=
# Skip directories
for file in $FILES_IGNORE; do
  if [ ! -d $file ]; then   
     FILES="$FILES $file"
  fi
done

# *** Files ins release directory kopieren
if [ -d "$ARC_NAME" ]; then
    echo "Archiv-Verzeichnis $ARC_NAME existiert schon!"
    echo "Weigerung, existierende Dateien zu überschreiben, bitte manuell löschen"
    exit 1
fi
mkdir $ARC_NAME
rsync --relative -v $FILES $ARC_NAME

# Create Examples
pushd $ARC_NAME/examples
./make_examples
popd

# *** Archiv erzeugen

echo Erzeuge Archiv $ARC_NAME.tar.bz2 ...
echo tar -cvjf $ARC_NAME.tar.bz2 $ARC_NAME/
tar -cvjf $ARC_NAME.tar.bz2 $ARC_NAME/

echo
echo Done
echo
