#!/bin/sh
# Rebuild examples


../gpx2map --merge -w ischgl-google --nospeed --notime --notemp ischgl.xml
../gpx2map --merge -w ischgl-osm --nospeed --notime --notemp --osm ischgl.xml

../gpx2map --merge -w juh-google --nospeed --notime --notemp juh.xml
../gpx2map --merge -w juh-osm --nospeed --notime --notemp --osm juh.xml

../gpx2map --merge -w monte_viso-google --nospeed --notime --notemp monte_viso.gpx
../gpx2map --merge -w monte_viso-osm --nospeed --notime --notemp --osm monte_viso.gpx

../gpx2map --merge -w native-speed-data-google --notemp native-speed-data.gpx
../gpx2map --merge -w native-speed-data-osm --notemp --osm native-speed-data.gpx
